sudo: required

language: node_js

node_js:

  - "8"

services:

  - docker

before_install:

  - docker pull trufflesuite/ganache-cli

  - docker run -d -p 8545:8545 trufflesuite/ganache-cli:latest -h 0.0.0.0
  
  - docker pull solc:0.4.25
  
install:

  - npm install -g truffle

  - npm install -g coveralls

  - npm install
  - brew unlink solidity
  - # Install 0.4.8
  - brew install https://raw.githubusercontent.com/ethereum/homebrew-ethereum/77cce03da9f289e5a3ffe579840d3c5dc0a62717/solidity.rb

script:

  - npm run coverage && cat coverage/lcov.info | coveralls
